# Site settings
title: Anuj Gupta blog
email: 
description: "datachurning"
baseurl: ""
url: "https://anujgupta82.github.io/"
twitter_username: anujgupta82
github_username:  anujgupta82

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
